name: epubx
description: Epub Parser for Dart. Epub package fork. Suitable for use on the Server, the Web, or in Flutter

version: 4.0.0
publish_to: "none" # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  archive: ^3.1.6
  quiver: ^3.0.1+1
  path: ^1.8.0
  xml: ^6.0.1
  image: 4.1.7
  collection: ^1.15.0

dev_dependencies:
  test: ^1.16.7
  pedantic: ^1.11.0
